version: '3.7'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    ports:
      - '3030:3030'
  frontend:
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    container_name: frontend
    tty: true
    stdin_open: true
    depends_on:
      - backend
    ports:
      - '3000:3000'
  postgres:
    image: postgres:14.1-alpine
    container_name: wefunder-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
volumes:
  pg_data:
