FROM golang:1.17-buster as base

RUN apt update && apt -y install git make bash htop tzdata gcc mupdf
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# copy the entire project up in here so we can build it
COPY . .

RUN make -B

EXPOSE 3030
CMD ["./build/run"]

